-- INIT DATABASE 
CREATE TABLE BOOK (
    book_id NUMBER PRIMARY KEY,
    title VARCHAR2(100),
    author VARCHAR2(50),
    category VARCHAR2(30),
    price NUMBER(8,2)
);

-- 5 RECORDS TO INSERT 
INSERT INTO BOOK VALUES (1, 'The Alchemist', 'Paulo Coelho', 'Fiction', 350);
INSERT INTO BOOK VALUES (2, 'Database System Concepts', 'Silberschatz', 'Education', 750);
INSERT INTO BOOK VALUES (3, 'Wings of Fire', 'A.P.J. Abdul Kalam', 'Biography', 400);
INSERT INTO BOOK VALUES (4, 'Harry Potter', 'J.K. Rowling', 'Fantasy', 500);
INSERT INTO BOOK VALUES (5, 'Clean Code', 'Robert C. Martin', 'Programming', 650);

-- DISPLAY ALL RECORDS 
SELECT * FROM BOOK;
DESC BOOK; 

-- DISPLAY FROM A PARTICULAR CATEGORY 
SELECT * FROM BOOK
WHERE category = 'Programming';
DESC BOOK;

-- UPDATING PRICE OF A BOOK 
UPDATE BOOK
SET price = 500
WHERE title = 'Clean Code';
DESC BOOK;

-- DELETING ONE BOOK FROM THE DATABASE 
DELETE FROM BOOK
WHERE title = 'Harry Potter';
DESC BOOK;

-- ADDING NEW COLUMNS 
ALTER TABLE BOOK ADD (publisher VARCHAR2(50));
ALTER TABLE BOOK ADD (rack_no NUMBER);
DESC BOOK;

-- UPDATING NEW COLUMNS
UPDATE BOOK
SET publisher = 'Penguin', rack_no = 12
WHERE book_id = 1; 

UPDATE BOOK
SET publisher = 'McGraw Hill', rack_no = 5
WHERE book_id = 2;
DESC BOOK;

-- MODIFYING DATATYPE OR SIZE OF THE PUBLISHER 
ALTER TABLE BOOK MODIFY (publisher VARCHAR2(100));
DESC BOOK;

-- DROPPING ANY COLUMN FROM THE DATABASE 
ALTER TABLE BOOK DROP COLUMN rack_no;
DESC BOOK;

-- RENAMING COLUMN OF DATABASE 
ALTER TABLE BOOK RENAME COLUMN title TO book_title;
DESC BOOK;

-- RENAMING TABLE & DROPPING IT IN THE END 
ALTER TABLE BOOK RENAME TO LIBRARY_BOOK;
DROP TABLE LIBRARY_BOOK;
