CREATE TABLE EMPLOYEE (
    EMP_NO INT PRIMARY KEY,
    E_NAME VARCHAR(100),
    E_ADDRESS VARCHAR(250),
    E_PH_NO INT,
    DEPT_NO INT,
    DEPT_NAME VARCHAR(100),
    JOB_ID CHAR(10),
    SALARY INT
);

ALTER TABLE EMPLOYEE
ADD HIREDATE DATE;

ALTER TABLE EMPLOYEE
MODIFY JOB_ID VARCHAR(20);

ALTER TABLE EMPLOYEE
CHANGE EMP_NO E_NO INT PRIMARY KEY;

ALTER TABLE EMPLOYEE
MODIFY JOB_ID VARCHAR(50);
